/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description List all persisted jobs, ranked strongest-match first.
         *
         *     Args:
         *         repository: The shared job repository (injected).
         *
         *     Returns:
         *         Every stored job as a lean card-shaped JobSummary.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * JobSummary
         * @description A single job as shown in the job-list screen (one JobCard).
         *
         *     Carries only what a card needs: identity, the deduplicated platforms it was
         *     seen on, and the score/threshold/near-miss-floor the ``<ThresholdRail>`` reads
         *     per job. The full nine-category breakdown lives on the (later) detail endpoint.
         */
        JobSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            /** Url */
            url: string | null;
            /** Platforms */
            platforms: string[];
            /** Score */
            score: number | null;
            /** Threshold */
            threshold: number | null;
            /** Nearmissfloor */
            nearMissFloor: number | null;
            /** Hirerecommendation */
            hireRecommendation: string | null;
            /** Senioritylevel */
            seniorityLevel: string | null;
            /**
             * Lastseenat
             * Format: date-time
             */
            lastSeenAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
        };
    };
}
