/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description List all persisted jobs, ranked strongest-match first.
         *
         *     Args:
         *         repository: The shared job repository (injected).
         *
         *     Returns:
         *         Every stored job as a lean card-shaped JobSummary.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Return the full detail fan-out for one job.
         *
         *     Args:
         *         job_id: The repository id of the job.
         *         repository: The shared job repository (injected).
         *
         *     Returns:
         *         The job's detail, including its score breakdown and status history.
         *
         *     Raises:
         *         HTTPException: 404 when no job has that id.
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Status
         * @description Transition a job to a human-set status, appending a history row.
         *
         *     A same-value write is an idempotent no-op (no history row) but still returns
         *     the current detail. Machine statuses are rejected by the request schema (422).
         *
         *     Args:
         *         job_id: The repository id of the job.
         *         body: The target status and an optional note.
         *         repository: The shared job repository (injected).
         *
         *     Returns:
         *         The job's refreshed detail after the write.
         *
         *     Raises:
         *         HTTPException: 404 when no job has that id.
         */
        patch: operations["update_status_api_jobs__job_id__status_patch"];
        trace?: never;
    };
    "/api/jobs/{job_id}/saved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Saved
         * @description Set a job's ``saved`` bookmark (never writes history).
         *
         *     Args:
         *         job_id: The repository id of the job.
         *         body: The bookmark value to set.
         *         repository: The shared job repository (injected).
         *
         *     Returns:
         *         The job's refreshed detail after the write.
         *
         *     Raises:
         *         HTTPException: 404 when no job has that id.
         */
        patch: operations["update_saved_api_jobs__job_id__saved_patch"];
        trace?: never;
    };
    "/api/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Resume
         * @description Return the active master resume and its version history.
         *
         *     Args:
         *         service: The shared ResumeService (injected).
         *
         *     Returns:
         *         The panel state — active version plus every version, newest-first. An empty
         *         store yields ``{active: null, versions: []}`` (a normal empty state).
         */
        get: operations["get_resume_api_resume_get"];
        put?: never;
        /**
         * Upload Resume
         * @description Parse and store an uploaded resume as the new active version.
         *
         *     Identical bytes to an existing version are re-activated, not re-parsed (ADR-028).
         *
         *     Args:
         *         file: The uploaded ``.pdf`` or ``.docx`` file.
         *         service: The shared ResumeService (injected).
         *
         *     Returns:
         *         The refreshed panel state after the upload.
         *
         *     Raises:
         *         HTTPException: 400 when the file is too large, empty, unparseable, or an
         *             unsupported format — with a clear message.
         */
        post: operations["upload_resume_api_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/versions/{version}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Version
         * @description Restore an earlier stored version as the active one.
         *
         *     Args:
         *         version: The version number to activate.
         *         service: The shared ResumeService (injected).
         *
         *     Returns:
         *         The refreshed panel state after the switch.
         *
         *     Raises:
         *         HTTPException: 404 when no version with that number exists.
         */
        post: operations["activate_version_api_resume_versions__version__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Generation
         * @description Start an async resume/cover-letter generation and return its pending record.
         *
         *     Preconditions (a stored master resume, a known job) are checked synchronously so
         *     a user-fixable problem is a clear 400 rather than a silently failed background job.
         *
         *     Args:
         *         job_id: The repository id of the job to generate for.
         *         body: The generation kind and, for a cover letter, the optional voice.
         *         background_tasks: FastAPI's post-response task runner.
         *         service: The shared GenerationService (injected).
         *
         *     Returns:
         *         The pending GenerationOut (poll it via ``GET /generations/{id}``).
         *
         *     Raises:
         *         HTTPException: 400 when no resume is stored or the job id is unknown.
         */
        post: operations["start_generation_api_jobs__job_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Job Generations
         * @description List every generation recorded for a job, newest first (the chip's initial state).
         *
         *     Args:
         *         job_id: The repository id of the job.
         *         service: The shared GenerationService (injected).
         *
         *     Returns:
         *         The job's generations as provenance-only response models.
         */
        get: operations["list_job_generations_api_jobs__job_id__generations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generations/{generation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll Generation
         * @description Return one generation's current state, flipping a timed-out pending row to failed.
         *
         *     Args:
         *         generation_id: The id returned by the generate call.
         *         service: The shared GenerationService (injected).
         *
         *     Returns:
         *         The generation's current GenerationOut.
         *
         *     Raises:
         *         HTTPException: 404 when no generation has that id.
         */
        get: operations["poll_generation_api_generations__generation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generations/{generation_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Generation
         * @description Stream a ready generation's ``.docx`` (never its content in JSON).
         *
         *     Args:
         *         generation_id: The id of the generation to download.
         *         service: The shared GenerationService (injected).
         *
         *     Returns:
         *         A FileResponse streaming the ``.docx`` with a friendly filename.
         *
         *     Raises:
         *         HTTPException: 404 unknown id; 409 not yet ready; 410 when the ``ready``
         *             row's file is missing on disk (the chip falls back to regenerate,
         *             ADR-034 §3).
         */
        get: operations["download_generation_api_generations__generation_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Return the global settings, the ``.env`` defaults, and masked secret status.
         */
        get: operations["get_settings_api_settings_get"];
        /**
         * Update Settings
         * @description Persist the editable global settings (provider allowlist enforced by the schema).
         *
         *     When the in-process scheduler is running, a saved cron/timezone reschedules it live
         *     by a direct method call (ADR-032) — no restart. An invalid cron never fails the save
         *     (the preview endpoint is where cron is validated); it is logged and left unscheduled.
         */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/secrets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Secret
         * @description Replace a secret (write-only). The value is stored, never returned.
         *
         *     Raises:
         *         HTTPException: 404 for an unknown secret name.
         */
        put: operations["set_secret_api_settings_secrets__name__put"];
        post?: never;
        /**
         * Clear Secret
         * @description Clear a secret's DB override, reverting to the ``.env`` value.
         *
         *     Raises:
         *         HTTPException: 404 for an unknown secret name.
         */
        delete: operations["clear_secret_api_settings_secrets__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/schedule/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Schedule Preview
         * @description Return the next 3 fire times for a cron expression (no live scheduler).
         *
         *     Raises:
         *         HTTPException: 400 for an invalid cron expression or timezone.
         */
        get: operations["schedule_preview_api_settings_schedule_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description List every stored search profile, ordered by position.
         */
        get: operations["list_profiles_api_profiles_get"];
        put?: never;
        /**
         * Create Profile
         * @description Create a new search profile.
         *
         *     Raises:
         *         HTTPException: 400 on an invalid location/work-type combination or enum value.
         */
        post: operations["create_profile_api_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Profile
         * @description Update an existing search profile.
         *
         *     Raises:
         *         HTTPException: 404 when the profile does not exist; 400 on invalid input.
         */
        put: operations["update_profile_api_profiles__profile_id__put"];
        post?: never;
        /**
         * Delete Profile
         * @description Delete a search profile.
         *
         *     Raises:
         *         HTTPException: 404 when the profile does not exist; 409 when it is the last
         *             remaining profile (a run must always have something to do).
         */
        delete: operations["delete_profile_api_profiles__profile_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description List recent runs, newest first (healing any run lost to a restart).
         *
         *     Args:
         *         limit: Maximum number of runs to return (1–100).
         *         service: The shared RunService (injected).
         *
         *     Returns:
         *         Up to ``limit`` runs as response models.
         */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /**
         * Start Run
         * @description Start a background pipeline run and return its ``running`` record.
         *
         *     Preconditions (no run already in progress, at least one profile) are checked
         *     synchronously so a user-fixable problem is a clear 4xx rather than a silently
         *     failed background run.
         *
         *     Args:
         *         background_tasks: FastAPI's post-response task runner.
         *         service: The shared RunService (injected).
         *
         *     Returns:
         *         The ``running`` RunOut (poll it via ``GET /runs/{id}``).
         *
         *     Raises:
         *         HTTPException: 409 when a run is already in progress; 400 when no search
         *             profiles are configured.
         */
        post: operations["start_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll Run
         * @description Return one run's current state, flipping a timed-out ``running`` row to failed.
         *
         *     Args:
         *         run_id: The id returned by the start call.
         *         service: The shared RunService (injected).
         *
         *     Returns:
         *         The run's current RunOut.
         *
         *     Raises:
         *         HTTPException: 404 when no run has that id.
         */
        get: operations["poll_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_resume_api_resume_post */
        Body_upload_resume_api_resume_post: {
            /** File */
            file: string;
        };
        /**
         * GenerateRequest
         * @description Request body for ``POST /jobs/{id}/generate`` — start an async generation.
         *
         *     ``voice`` applies only to a cover letter; when omitted the router seeds the
         *     env-configured default voice (the in-browser voice form arrives with W7).
         */
        GenerateRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "resume" | "cover_letter";
            voice?: components["schemas"]["VoiceIn"] | null;
        };
        /**
         * GenerationOut
         * @description One generated-document record for the chip, provenance only (ui-spec §5.4/§7).
         *
         *     Carries the async ``status``, the formatter ``outcome`` (only meaningful once
         *     ``status == "ready"`` — surfaced as null while pending/failed), the repair note,
         *     and the structural ``reviewLocations`` for a ``needs_review`` outcome. It
         *     **never** carries document content or the server-side ``file_path``: the client
         *     reaches the file through ``GET /generations/{id}/download`` (ADR-034 §3).
         */
        GenerationOut: {
            /** Id */
            id: string;
            /** Jobid */
            jobId: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "resume" | "cover_letter";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "ready" | "failed";
            /** Outcome */
            outcome: ("clean" | "repaired" | "needs_review") | null;
            /** Reviewlocations */
            reviewLocations: string[];
            /** Repairnote */
            repairNote: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobDetail
         * @description The full detail fan-out for one job (ui-spec §6.1).
         *
         *     Everything ``JobSummary`` carries plus the nine-category breakdown, matched /
         *     missing skills, the description, the lifecycle (status, saved, history), and a
         *     ``generations`` stub (populated once F ships). Never carries generated-document
         *     content or raw resume text (ui-spec §7).
         */
        JobDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            /** Url */
            url: string | null;
            /** Description */
            description: string | null;
            /** Platforms */
            platforms: string[];
            /** Score */
            score: number | null;
            /** Threshold */
            threshold: number | null;
            /** Nearmissfloor */
            nearMissFloor: number | null;
            /** Hirerecommendation */
            hireRecommendation: string | null;
            /** Senioritylevel */
            seniorityLevel: string | null;
            /** Yearsexperiencedetected */
            yearsExperienceDetected: number | null;
            /** Summary */
            summary: string | null;
            /** Matchedskills */
            matchedSkills: string[];
            /** Missingskills */
            missingSkills: string[];
            /** Scorebreakdown */
            scoreBreakdown: components["schemas"]["ScoreCategoryRow"][] | null;
            /** Status */
            status: string;
            /** Saved */
            saved: boolean;
            /** Statushistory */
            statusHistory: components["schemas"]["StatusHistoryEntryOut"][];
            /**
             * Generations
             * @default []
             */
            generations: unknown[];
            /**
             * Lastseenat
             * Format: date-time
             */
            lastSeenAt: string;
        };
        /**
         * JobSummary
         * @description A single job as shown in the job-list screen (one JobCard).
         *
         *     Carries only what a card needs: identity, the deduplicated platforms it was
         *     seen on, and the score/threshold/near-miss-floor the ``<ThresholdRail>`` reads
         *     per job. The full nine-category breakdown lives on the (later) detail endpoint.
         */
        JobSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            /** Url */
            url: string | null;
            /** Platforms */
            platforms: string[];
            /** Score */
            score: number | null;
            /** Threshold */
            threshold: number | null;
            /** Nearmissfloor */
            nearMissFloor: number | null;
            /** Hirerecommendation */
            hireRecommendation: string | null;
            /** Senioritylevel */
            seniorityLevel: string | null;
            /** Status */
            status: string;
            /** Saved */
            saved: boolean;
            /**
             * Lastseenat
             * Format: date-time
             */
            lastSeenAt: string;
        };
        /**
         * PricingOut
         * @description The configured token pricing, surfaced read-only on the provider cards.
         *
         *     Rates live in ``.env`` (``docs/env.md`` is the source of truth) and always display;
         *     ``show_cost_estimate`` reflects ``SHOW_COST_ESTIMATE`` so the UI can note that the
         *     rates only *apply* to tracking when it is enabled. Never writable (no differs-from-.env
         *     semantics) — absent from ``SettingsUpdate`` and ``SettingsDefaults``.
         */
        PricingOut: {
            /** Showcostestimate */
            showCostEstimate: boolean;
            openai: components["schemas"]["ProviderRates"];
            anthropic: components["schemas"]["ProviderRates"];
        };
        /**
         * ProfileIn
         * @description Request body for creating/updating a search profile.
         */
        ProfileIn: {
            /**
             * Name
             * @default
             */
            name: string;
            /** Query */
            query: string;
            /** Location */
            location?: string | null;
            /** Worktypes */
            workTypes?: string[] | null;
            /**
             * Dateposted
             * @default 3days
             */
            datePosted: string | null;
            /**
             * Activescrapers
             * @default [
             *       "linkedin",
             *       "indeed",
             *       "glassdoor",
             *       "ziprecruiter"
             *     ]
             */
            activeScrapers: string[];
            /**
             * Scorethreshold
             * @default 75
             */
            scoreThreshold: number;
            /** Topresults */
            topResults?: number | null;
        };
        /**
         * ProfileOut
         * @description One stored search profile as the Settings UI sees it.
         */
        ProfileOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Query */
            query: string;
            /** Location */
            location: string;
            /** Worktypes */
            workTypes: string[] | null;
            /** Dateposted */
            datePosted: string | null;
            /** Activescrapers */
            activeScrapers: string[];
            /** Scorethreshold */
            scoreThreshold: number;
            /** Topresults */
            topResults: number | null;
        };
        /**
         * ProviderRates
         * @description One provider's configured per-1M-token rates (read-only, ``.env``-owned).
         */
        ProviderRates: {
            /** Inputper1M */
            inputPer1M: number;
            /** Outputper1M */
            outputPer1M: number;
        };
        /**
         * ResumeOut
         * @description One stored master-resume version, provenance only (ui-spec §14.2).
         *
         *     Carries *about* the resume — version, source file, size, parsed counts, which
         *     version is active — never the resume text itself (``raw_text``) or its content
         *     hash. The privacy boundary (ADR-028): resume content never leaves the API.
         */
        ResumeOut: {
            /** Version */
            version: number;
            /** Filename */
            filename: string;
            /** Sizebytes */
            sizeBytes: number;
            /** Skillcount */
            skillCount: number;
            /** Rolecount */
            roleCount: number;
            /** Isactive */
            isActive: boolean;
            /** Uploadedat */
            uploadedAt: string | null;
        };
        /**
         * ResumeState
         * @description The master-resume panel's full read model — active version plus history.
         *
         *     ``versions`` is newest-first; ``active`` is the one with ``is_active`` (or None
         *     when nothing is stored yet — a normal empty state, not an error).
         */
        ResumeState: {
            active: components["schemas"]["ResumeOut"] | null;
            /** Versions */
            versions: components["schemas"]["ResumeOut"][];
        };
        /**
         * RunOut
         * @description One run's lifecycle + summary for the "Run search now" control (W8).
         *
         *     Carries the async ``status`` and the summary counts (only meaningful once
         *     ``status == "succeeded"``), the trigger, and timing. ``error`` is a bare
         *     exception *type name* on a failed run — never a raw message (CLAUDE.md #2).
         *     It carries no job content: the evaluated jobs land in the job list, which the
         *     client refetches when a run succeeds.
         */
        RunOut: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "web" | "scheduled" | "cli";
            /** Profilesrun */
            profilesRun: number;
            /** Jobsfound */
            jobsFound: number;
            /** Newjobs */
            newJobs: number;
            /** Qualifying */
            qualifying: number;
            /** Error */
            error: string;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /** Finishedat */
            finishedAt: string | null;
        };
        /**
         * SavedUpdate
         * @description Request body for ``PATCH /jobs/{id}/saved`` — the bookmark toggle.
         */
        SavedUpdate: {
            /** Saved */
            saved: boolean;
        };
        /**
         * SchedulePreview
         * @description The next few cron fire times for the schedule preview.
         */
        SchedulePreview: {
            /** Nextruns */
            nextRuns: string[];
        };
        /**
         * ScoreCategoryRow
         * @description One row of the nine-category score breakdown, in rubric order.
         *
         *     ``category`` is the domain field name (e.g. ``role_alignment``); the frontend
         *     formats it into a label. Emitting an ordered list keeps the rubric order
         *     backend-owned and the component generic.
         */
        ScoreCategoryRow: {
            /** Category */
            category: string;
            /** Earned */
            earned: number;
            /** Max */
            max: number;
            /** Reasoning */
            reasoning: string;
        };
        /**
         * SecretStatus
         * @description A secret's masked status — never its value (ADR-031).
         */
        SecretStatus: {
            /** Name */
            name: string;
            /** Configured */
            configured: boolean;
            /** Masked */
            masked: string;
            /** Overridden */
            overridden: boolean;
        };
        /**
         * SecretUpdate
         * @description Request body for ``PUT /api/settings/secrets/{name}`` — a write-only replace.
         */
        SecretUpdate: {
            /** Value */
            value: string;
        };
        /**
         * SettingsDefaults
         * @description The `.env`-derived global settings, for the UI's differs-from-.env diff.
         */
        SettingsDefaults: {
            /** Evaluatorprovider */
            evaluatorProvider: string;
            /** Evaluatormodel */
            evaluatorModel: string | null;
            /** Schedulecron */
            scheduleCron: string;
            /** Scheduletimezone */
            scheduleTimezone: string;
            /** Enrichmentmode */
            enrichmentMode: string;
            voice: components["schemas"]["VoiceIn"];
        };
        /**
         * SettingsOut
         * @description The global settings screen state — effective values + the ``.env`` defaults.
         *
         *     ``envDefaults`` lets the UI show a "differs from .env" indicator per field
         *     (ADR-031). ``secrets`` carries **masked** status only — never a key value.
         *     ``pricing`` is read-only configured token rates (never in ``SettingsUpdate``).
         */
        SettingsOut: {
            /** Evaluatorprovider */
            evaluatorProvider: string;
            /** Evaluatormodel */
            evaluatorModel: string | null;
            /** Schedulecron */
            scheduleCron: string;
            /** Scheduletimezone */
            scheduleTimezone: string;
            /** Enrichmentmode */
            enrichmentMode: string;
            voice: components["schemas"]["VoiceIn"];
            envDefaults: components["schemas"]["SettingsDefaults"];
            /** Secrets */
            secrets: components["schemas"]["SecretStatus"][];
            pricing: components["schemas"]["PricingOut"];
        };
        /**
         * SettingsUpdate
         * @description Request body for ``PUT /api/settings`` — the editable global settings.
         */
        SettingsUpdate: {
            /**
             * Evaluatorprovider
             * @enum {string}
             */
            evaluatorProvider: "openai" | "anthropic";
            /** Evaluatormodel */
            evaluatorModel?: string | null;
            /**
             * Schedulecron
             * @default
             */
            scheduleCron: string;
            /**
             * Scheduletimezone
             * @default UTC
             */
            scheduleTimezone: string;
            /**
             * Enrichmentmode
             * @default shadow
             * @enum {string}
             */
            enrichmentMode: "shadow" | "enforce";
            /**
             * @default {
             *       "tone": "direct",
             *       "person": "first_person",
             *       "styleNotes": ""
             *     }
             */
            voice: components["schemas"]["VoiceIn"];
        };
        /**
         * StatusHistoryEntryOut
         * @description A status-history row for the detail screen's action timeline (ADR-025).
         */
        StatusHistoryEntryOut: {
            /** Fromstatus */
            fromStatus: string | null;
            /** Tostatus */
            toStatus: string;
            /** Note */
            note: string | null;
            /**
             * Changedat
             * Format: date-time
             */
            changedAt: string;
        };
        /**
         * StatusUpdate
         * @description Request body for ``PATCH /jobs/{id}/status`` — a human status write.
         */
        StatusUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "started" | "interviewing" | "offer" | "rejected" | "not_interested";
            /** Note */
            note?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VoiceIn
         * @description Optional cover-letter voice on a generate request (ADR-030, structured only).
         */
        VoiceIn: {
            /**
             * Tone
             * @default direct
             * @enum {string}
             */
            tone: "direct" | "warm" | "formal" | "bold";
            /**
             * Person
             * @default first_person
             * @enum {string}
             */
            person: "first_person" | "implied";
            /**
             * Stylenotes
             * @default
             */
            styleNotes: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_status_api_jobs__job_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_saved_api_jobs__job_id__saved_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_api_resume_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeState"];
                };
            };
        };
    };
    upload_resume_api_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_resume_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_version_api_resume_versions__version__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_generation_api_jobs__job_id__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_job_generations_api_jobs__job_id__generations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    poll_generation_api_generations__generation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_generation_api_generations__generation_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_secret_api_settings_secrets__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_secret_api_settings_secrets__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_preview_api_settings_schedule_preview_get: {
        parameters: {
            query: {
                cron: string;
                timezone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_api_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"][];
                };
            };
        };
    };
    create_profile_api_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_profiles__profile_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_api_profiles__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
        };
    };
    poll_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
